# Generated by Django 2.2.7 on 2020-01-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('recipe', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='(no title)', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='(no title)', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cocktail')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1.0)),
                ('cocktail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='app.Cocktail')),
                ('ingredient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tags',
            field=models.ManyToManyField(related_name='cocktails', through='app.CocktailTag', to='app.Tag'),
        ),
    ]
